# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_despacho_notarial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despacho_notarial',
            name='nombre',
            field=models.CharField(max_length=124, verbose_name='Despacho Notarial'),
        ),
    ]
