# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-23 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import evaluacion.models
import evaluacion.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaluos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_avaluo', models.DateField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_hectarea', models.DecimalField(decimal_places=2, max_digits=12)),
                ('documento', models.FileField(blank=True, null=True, upload_to=evaluacion.models.Avaluos.file_path, validators=[evaluacion.validators.valid_extension_pdf])),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('lonja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.Lonja')),
            ],
        ),
        migrations.CreateModel(
            name='Caracterizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_caracterizacion', models.DateField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('acueducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.Acueducto')),
                ('bocatoma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.Bocatoma')),
                ('cuenca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.Cuenca')),
            ],
        ),
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=evaluacion.models.Fotos.imagen_path)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ofertas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombres')),
                ('apellido1', models.CharField(max_length=32, verbose_name='Primer Apellido')),
                ('apellido2', models.CharField(blank=True, max_length=32, null=True, verbose_name='Segundo Apellido')),
                ('cedula', models.IntegerField()),
                ('direccion', models.CharField(blank=True, max_length=124, null=True, verbose_name='Direccion')),
                ('telefono', models.CharField(blank=True, max_length=24, null=True, verbose_name='Telefono')),
                ('documento', models.FileField(blank=True, null=True, upload_to=evaluacion.models.Ofertas.file_path, validators=[evaluacion.validators.valid_extension_pdf])),
                ('fecha_oferta', models.DateField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.Municipios')),
            ],
        ),
        migrations.CreateModel(
            name='Predios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Predio')),
                ('matricula', models.CharField(max_length=12, unique=True, verbose_name='Nº Matricula')),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('kml', models.FileField(blank=True, null=True, upload_to=evaluacion.models.Predios.file_path, validators=[evaluacion.validators.valid_extension_kml])),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.EstadoPredio')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.Municipios')),
                ('vereda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.Veredas')),
            ],
        ),
        migrations.CreateModel(
            name='Titularidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('fecha_documento', models.DateField(blank=True, null=True)),
                ('documento', models.FileField(blank=True, null=True, upload_to=evaluacion.models.Titularidad.file_path, validators=[evaluacion.validators.valid_extension_pdf])),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('predio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.Predios')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.TipoTitularidad')),
                ('tipo_impedimento', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.TipoImpedimento')),
            ],
        ),
        migrations.CreateModel(
            name='Topografia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_topografia', models.DateField()),
                ('area_total', models.DecimalField(decimal_places=4, max_digits=11)),
                ('area_bosque', models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True)),
                ('area_sabana', models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True)),
                ('area_agricola', models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True)),
                ('documento', models.FileField(blank=True, null=True, upload_to=evaluacion.models.Topografia.file_path, validators=[evaluacion.validators.valid_extension_pdf])),
                ('plano', models.FileField(blank=True, null=True, upload_to=evaluacion.models.Topografia.file_path, validators=[evaluacion.validators.valid_extension_pdf])),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('predio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.Predios')),
            ],
        ),
        migrations.AddField(
            model_name='ofertas',
            name='predio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.Predios'),
        ),
        migrations.AddField(
            model_name='fotos',
            name='predio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.Predios'),
        ),
        migrations.AddField(
            model_name='caracterizacion',
            name='predio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.Predios'),
        ),
        migrations.AddField(
            model_name='caracterizacion',
            name='presencia_hidrica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.TipoPresenciaHidrica'),
        ),
        migrations.AddField(
            model_name='avaluos',
            name='predio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.Predios'),
        ),
    ]
