# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-15 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predios',
            name='matricula',
            field=models.CharField(max_length=12, unique=True, verbose_name='Folio Matricula inmobiliaria'),
        ),
    ]
