# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-22 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0004_auto_20160721_2329'),
        ('evaluacion', '0002_auto_20160715_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caracterizacion',
            name='bocatoma',
        ),
        migrations.RemoveField(
            model_name='caracterizacion',
            name='cuenca',
        ),
        migrations.RemoveField(
            model_name='caracterizacion',
            name='presencia_hidrica',
        ),
        migrations.AddField(
            model_name='caracterizacion',
            name='microcuenca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Microcuenca'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caracterizacion',
            name='subzona',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Subzona'),
            preserve_default=False,
        ),
    ]
