# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import evaluacion.models
import evaluacion.validators


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0003_auto_20160722_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='caracterizacion',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to=evaluacion.models.Caracterizacion.file_path, validators=[evaluacion.validators.valid_extension_pdf]),
        ),
    ]
