# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-22 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluacion', '0003_auto_20160722_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=8)),
                ('valor', models.DecimalField(decimal_places=1, max_digits=16)),
                ('tiempo_ejecucion', models.DecimalField(decimal_places=1, max_digits=4)),
                ('fecha_inicio', models.DateField()),
                ('fecha_terminacion', models.DateField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contratos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.IntegerField()),
                ('fecha_contrato', models.DateField()),
                ('valor_contrato', models.DecimalField(decimal_places=2, max_digits=16)),
                ('contratista', models.CharField(max_length=200, verbose_name='Nombres')),
                ('representante', models.CharField(max_length=200, verbose_name='representante')),
                ('nit', models.CharField(blank=True, max_length=200, null=True, verbose_name='nit')),
                ('direccion', models.CharField(blank=True, max_length=200, null=True, verbose_name='direccion')),
                ('tiempo_ejecucion', models.DecimalField(decimal_places=1, max_digits=4)),
                ('fecha_inicio', models.DateField()),
                ('fecha_terminacion', models.DateField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoActividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre Municipio')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='actividades',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.TipoActividad'),
        ),
        migrations.AddField(
            model_name='actividades',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.Contratos'),
        ),
        migrations.AddField(
            model_name='actividades',
            name='predio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.Predios'),
        ),
    ]
