# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-15 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0002_despacho_notarial'),
        ('evaluacion', '0002_auto_20160715_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contratos_adquisicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.IntegerField()),
                ('fecha_contrato', models.DateField()),
                ('valor_contrato', models.DecimalField(decimal_places=2, max_digits=16)),
                ('nombre_vendedor', models.CharField(max_length=200, verbose_name='Nombre')),
                ('apellido1_vendedor', models.CharField(max_length=200, verbose_name='Primer Apellido')),
                ('apellido2_vendedor', models.CharField(blank=True, max_length=200, null=True, verbose_name='Segundo Apellido')),
                ('identificacion_vendedor', models.IntegerField()),
                ('direccion_vendedor', models.CharField(blank=True, max_length=200, null=True, verbose_name='direccion')),
                ('numero_escritura', models.IntegerField()),
                ('fecha_escritura', models.DateField()),
                ('folio_matricula', models.CharField(max_length=12, unique=True, verbose_name='Folio Matricula inmobiliaria')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('despacho_notarial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.Despacho_notarial')),
                ('predio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.Predios')),
            ],
        ),
    ]
