# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-21 18:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adquisicion', '0002_contratos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratos_adquisicion',
            name='despacho_notarial',
        ),
        migrations.RemoveField(
            model_name='contratos_adquisicion',
            name='predio',
        ),
        migrations.DeleteModel(
            name='Contratos_adquisicion',
        ),
    ]
