# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-22 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adquisicion', '0003_auto_20160721_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratos',
            name='nombre_vendedor',
            field=models.CharField(max_length=200, verbose_name='Nombres'),
        ),
    ]
